repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      - id: ruff-check
        args: [--config, pyproject.toml, --fix]
        stages: [pre-commit]
      - id: ruff-format
        args: [--config, pyproject.toml]
        stages: [pre-commit]
      - id: ruff-check
        args: [--config, pyproject.toml]
        stages: [manual]
      - id: ruff-format
        args: [--config, pyproject.toml]
        stages: [manual]